### PR TITLE
fixed null pointer and example added

### PR DESCRIPTION
**Pull request by jensgoe**

### CODE REVIEW

**Comment by jensgoe** [comment]
i missed some checks if wxDV_VARIABLE_LINE_HEIGHT flag is not set but then accessing the m_rowHeightCache member. I was thinking about to additionally check for m_rowHeightCache != NULL. It may be necessary only if the flags can change after the constructor has passed. Because only there the m_rowHeightCache member gets initialized. Do you know if this can happen?

**Comment by vadz** [comment]
In principle, there is `wxWindow::SetWindowStyleFlag()`, although we could override it in the generic wxDVC to forbid changing this flag after creation (because it really doesn't make much sense to allow it).

**Comment by vadz** [comment]
P.S. Maybe we should just check for `m_rowHeightCache` directly instead of checking for the flag?

**Comment by vadz** [comment]
Thanks, I've merged this into https://github.com/wxWidgets/wxWidgets/pull/1053, if no new problems are discovered, I'll merge it into master soon.

**Pull request closed without merging**
